export const actions = {
  assets: {
    GetAsset: () => import('#actions/assets/get_asset'),
    ShowAsset: () => import('#actions/assets/show_asset'),
    StoreAsset: () => import('#actions/assets/store_asset'),
  },
  auth: {
    DestroyExpiredSessions: () => import('#actions/auth/destroy_expired_sessions'),
    DestroySession: () => import('#actions/auth/destroy_session'),
    ForceSignout: () => import('#actions/auth/force_signout'),
    GetPaginatedSessions: () => import('#actions/auth/get_paginated_sessions'),
    GetSessionLogToken: () => import('#actions/auth/get_session_log_token'),
    OnAuthenticationFailed: () => import('#actions/auth/on_authentication_failed'),
    OnAuthenticationSucceeded: () => import('#actions/auth/on_authentication_succeeded'),
    OnSigninSucceeded: () => import('#actions/auth/on_signin_succeeded'),
    OnSignoutSucceeded: () => import('#actions/auth/on_signout_succeeded'),
    password: {
      RenderForgotPasswordSent: () => import('#actions/auth/password/render_forgot_password_sent'),
      RenderForgotPassword: () => import('#actions/auth/password/render_forgot_password'),
      RenderResetPassword: () => import('#actions/auth/password/render_reset_password'),
      ResetPassword: () => import('#actions/auth/password/reset_password'),
      SendForgotPassword: () => import('#actions/auth/password/send_forgot_password'),
    },
    RenderSigninPage: () => import('#actions/auth/render_signin_page'),
    RenderSignupPage: () => import('#actions/auth/render_signup_page'),
    social: {
      GetAllyUser: () => import('#actions/auth/social/get_ally_user'),
      HandleAllyCallback: () => import('#actions/auth/social/handle_ally_callback'),
      HandleAllyRedirect: () => import('#actions/auth/social/handle_ally_redirect'),
      HandleAllyUnlink: () => import('#actions/auth/social/handle_ally_unlink'),
    },
    StoreSessionLog: () => import('#actions/auth/store_session_log'),
    StoreSessionSignin: () => import('#actions/auth/store_session_signin'),
    StoreSessionSignup: () => import('#actions/auth/store_session_signup'),
  },
  Base: () => import('#actions/base_action'),
  collections: {
    GetSeriesLessonAtNumber: () => import('#actions/collections/get_series_lesson_at_number'),
    GetSeriesList: () => import('#actions/collections/get_series_list'),
    GetSeriesPaginated: () => import('#actions/collections/get_series_paginated'),
    GetSeriesRecentlyUpdated: () => import('#actions/collections/get_series_recently_updated'),
    GetSeries: () => import('#actions/collections/get_series'),
    RenderSeriesIndex: () => import('#actions/collections/render_series_index'),
    RenderSeriesShow: () => import('#actions/collections/render_series_show'),
    ToggleSeriesWatchlist: () => import('#actions/collections/toggle_series_watchlist'),
  },
  comments: {
    DestroyComment: () => import('#actions/comments/destroy_comment'),
    GetComments: () => import('#actions/comments/get_comments'),
    StoreComment: () => import('#actions/comments/store_comment'),
    ToggleCommentVote: () => import('#actions/comments/toggle_comment_vote'),
    UpdateComment: () => import('#actions/comments/update_comment'),
  },
  discussions: {
    DestroyDiscussion: () => import('#actions/discussions/destroy_discussion'),
    GetDiscussion: () => import('#actions/discussions/get_discussion'),
    GetDiscussionsPaginated: () => import('#actions/discussions/get_discussions_paginated'),
    RenderDiscussionsCreate: () => import('#actions/discussions/render_discussions_create'),
    RenderDiscussionsEdit: () => import('#actions/discussions/render_discussions_edit'),
    RenderDiscussionsIndex: () => import('#actions/discussions/render_discussions_index'),
    RenderDiscussionsShow: () => import('#actions/discussions/render_discussions_show'),
    StoreDiscussionView: () => import('#actions/discussions/store_discussion_view'),
    StoreDiscussion: () => import('#actions/discussions/store_discussion'),
    ToggleDiscussionSolvedAt: () => import('#actions/discussions/toggle_discussion_solved_at'),
    ToggleDiscussionVote: () => import('#actions/discussions/toggle_discussion_vote'),
    UpdateDiscussion: () => import('#actions/discussions/update_discussion'),
  },
  general: {
    GetIpAddress: () => import('#actions/general/get_ip_address'),
    GetIpLocation: () => import('#actions/general/get_ip_location'),
    GetRouteReferrer: () => import('#actions/general/get_route_referrer'),
    GetSiteStats: () => import('#actions/general/get_site_stats'),
    GetUserAgent: () => import('#actions/general/get_user_agent'),
    RenderFrag: () => import('#actions/general/render_frag'),
    RenderHome: () => import('#actions/general/render_home'),
    RenderOgImage: () => import('#actions/general/render_og_image'),
    RenderPricing: () => import('#actions/general/render_pricing'),
    RenderSchedule: () => import('#actions/general/render_schedule'),
    RenderSearch: () => import('#actions/general/render_search'),
    SendContactEmail: () => import('#actions/general/send_contact_email'),
    ToggleVote: () => import('#actions/general/toggle_vote'),
  },
  integrations: {
    github: {
      DownloadRepoZip: () => import('#actions/integrations/github/download_repo_zip'),
      PopulateGithubUsernameFromId: () => import('#actions/integrations/github/populate_github_username_from_id'),
      RemoveUserFromGithubTeam: () => import('#actions/integrations/github/remove_user_from_github_team'),
      SendGithubTeamInvite: () => import('#actions/integrations/github/send_github_team_invite'),
      SyncUserGithubTeamMembership: () => import('#actions/integrations/github/sync_user_github_team_membership'),
    },
    stripe: {
      HandleStripeCheckoutSuccess: () => import('#actions/integrations/stripe/handle_stripe_checkout_success'),
      HandleStripeWebhook: () => import('#actions/integrations/stripe/handle_stripe_webhook'),
      RedirectStripeCheckout: () => import('#actions/integrations/stripe/redirect_stripe_checkout'),
      RedirectStripePortal: () => import('#actions/integrations/stripe/redirect_stripe_portal'),
    },
  },
  notes: {
    DestroyLessonNote: () => import('#actions/notes/destroy_lesson_note'),
    DestroyNote: () => import('#actions/notes/destroy_note'),
    GetNote: () => import('#actions/notes/get_note'),
    GetNotes: () => import('#actions/notes/get_notes'),
    GetPostNotes: () => import('#actions/notes/get_post_notes'),
    RenderNoteEdit: () => import('#actions/notes/render_note_edit'),
    RenderNotesIndex: () => import('#actions/notes/render_notes_index'),
    RenderNotesShow: () => import('#actions/notes/render_notes_show'),
    StoreNote: () => import('#actions/notes/store_note'),
    UpdateNote: () => import('#actions/notes/update_note'),
  },
  notifications: {
    DestroyNotification: () => import('#actions/notifications/destroy_notification'),
    DisableAllNotifications: () => import('#actions/notifications/disable_all_notifications'),
    DisableNotification: () => import('#actions/notifications/disable_notification'),
    GetMentions: () => import('#actions/notifications/get_mentions'),
    GetNewMentions: () => import('#actions/notifications/get_new_mentions'),
    GetNotifications: () => import('#actions/notifications/get_notifications'),
    GetUnreadNotificationCount: () => import('#actions/notifications/get_unread_notification_count'),
    GotoNotification: () => import('#actions/notifications/goto_notification'),
    MarkNotificationRead: () => import('#actions/notifications/mark_notification_read'),
    SendCommentNotification: () => import('#actions/notifications/send_comment_notification'),
    SendMentionNotification: () => import('#actions/notifications/send_mention_notification'),
    SendNotification: () => import('#actions/notifications/send_notification'),
  },
  posts: {
    blogs: {
      GetBlog: () => import('#actions/posts/blogs/get_blog'),
      GetBlogsPaginated: () => import('#actions/posts/blogs/get_blogs_paginated'),
      RenderBlogsIndex: () => import('#actions/posts/blogs/render_blogs_index'),
      RenderBlogsShow: () => import('#actions/posts/blogs/render_blogs_show'),
    },
    GetTranscript: () => import('#actions/posts/get_transcript'),
    lessons: {
      GetLesson: () => import('#actions/posts/lessons/get_lesson'),
      GetLessonsLatest: () => import('#actions/posts/lessons/get_lessons_latest'),
      GetLessonsPaginated: () => import('#actions/posts/lessons/get_lessons_paginated'),
      RenderLessonsIndex: () => import('#actions/posts/lessons/render_lessons_index'),
      RenderLessonsShow: () => import('#actions/posts/lessons/render_lessons_show'),
    },
    SetDefaultPostPanel: () => import('#actions/posts/set_default_post_panel'),
    snippets: {
      GetSnippet: () => import('#actions/posts/snippets/get_snippet'),
      GetSnippetsPaginated: () => import('#actions/posts/snippets/get_snippets_paginated'),
      RenderSnippetsIndex: () => import('#actions/posts/snippets/render_snippets_index'),
      RenderSnippetsShow: () => import('#actions/posts/snippets/render_snippets_show'),
    },
    streams: {
      GetStreamsPaginated: () => import('#actions/posts/streams/get_streams_paginated'),
      RenderStreamsIndex: () => import('#actions/posts/streams/render_streams_index'),
    },
    TogglePostAutoplay: () => import('#actions/posts/toggle_post_autoplay'),
    TogglePostWatchlist: () => import('#actions/posts/toggle_post_watchlist'),
  },
  progress: {
    GetOrCreateProgress: () => import('#actions/progress/get_or_create_progress'),
    StoreProgress: () => import('#actions/progress/store_progress'),
    ToggleProgressCompletion: () => import('#actions/progress/toggle_progress_completion'),
  },
  syndication: {
    RenderRssXml: () => import('#actions/syndication/render_rss_xml'),
    RenderSitemapXml: () => import('#actions/syndication/render_sitemap_xml'),
    RenderSitemap: () => import('#actions/syndication/render_sitemap'),
  },
  taxonomies: {
    GetTopicList: () => import('#actions/taxonomies/get_topic_list'),
    GetTopic: () => import('#actions/taxonomies/get_topic'),
    GetTopicsFilter: () => import('#actions/taxonomies/get_topics_filter'),
    RenderTopicShowDiscussions: () => import('#actions/taxonomies/render_topic_show_discussions'),
    RenderTopicShowLessons: () => import('#actions/taxonomies/render_topic_show_lessons'),
    RenderTopicShowSeries: () => import('#actions/taxonomies/render_topic_show_series'),
    RenderTopicShowSnippets: () => import('#actions/taxonomies/render_topic_show_snippets'),
    RenderTopicShow: () => import('#actions/taxonomies/render_topic_show'),
    RenderTopicsIndex: () => import('#actions/taxonomies/render_topics_index'),
  },
  testimonials: {
    DestroyTestimonial: () => import('#actions/testimonials/destroy_testimonial'),
    GetUserTestimonials: () => import('#actions/testimonials/get_user_testimonials'),
    RenderTestimonialForm: () => import('#actions/testimonials/render_testimonial_form'),
    RenderUserTestimonials: () => import('#actions/testimonials/render_user_testimonials'),
    StoreTestimonial: () => import('#actions/testimonials/store_testimonial'),
    UpdateTestimonial: () => import('#actions/testimonials/update_testimonial'),
  },
  users: {
    CheckUserPostAccess: () => import('#actions/users/check_user_post_access'),
    DestroyAccount: () => import('#actions/users/destroy_account'),
    GetUserActivity: () => import('#actions/users/get_user_activity'),
    GetUserMentionAutocomplete: () => import('#actions/users/get_user_mention_autocomplete'),
    GetUserProfile: () => import('#actions/users/get_user_profile'),
    GetUserStats: () => import('#actions/users/get_user_stats'),
    RenderUserBookmarks: () => import('#actions/users/render_user_bookmarks'),
    RenderUserHistory: () => import('#actions/users/render_user_history'),
    RenderUserMenu: () => import('#actions/users/render_user_menu'),
    RenderUserProfile: () => import('#actions/users/render_user_profile'),
    RenderUserWatchlist: () => import('#actions/users/render_user_watchlist'),
    SendEmailVerification: () => import('#actions/users/send_email_verification'),
    settings: {
      PatchUserPreferences: () => import('#actions/users/settings/patch_user_preferences'),
      RenderUserInvoice: () => import('#actions/users/settings/render_user_invoice'),
      RenderUserSettings: () => import('#actions/users/settings/render_user_settings'),
      RevertEmail: () => import('#actions/users/settings/revert_email'),
      UpdateEmail: () => import('#actions/users/settings/update_email'),
      UpdateUserBillto: () => import('#actions/users/settings/update_user_billto'),
      UpdateUserNotifications: () => import('#actions/users/settings/update_user_notifications'),
      UpdateUserPreferences: () => import('#actions/users/settings/update_user_preferences'),
      UpdateUserProfile: () => import('#actions/users/settings/update_user_profile'),
      UpdateUsername: () => import('#actions/users/settings/update_username'),
    },
    UpdateUserTheme: () => import('#actions/users/update_user_theme'),
    VerifyEmail: () => import('#actions/users/verify_email'),
  },
}
